"""projects model and enum for type

Revision ID: 335450cc0808
Revises: a9fb80627de2
Create Date: 2026-02-20 23:21:57.488934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '335450cc0808'
down_revision: Union[str, Sequence[str], None] = 'a9fb80627de2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('project_type', sa.Enum('COMPUTER_SCIENCE', 'ELECTRICAL', 'MECHANICAL', 'ARTIFICIAL_INTELLIGENCE', name='projecttype'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    # ### end Alembic commands ###
